#pragma config(Motor,  port1,           Left,          tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,           Right,         tmotorVex393_MC29, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
motor [Left] = 127;
motor [Right] = 127;
wait1Msec(1000);

motor [Left] = 0;
motor [Right] = 0;

}
